Repository BhattAnsh/Quiz-Quest, pull requests merged in 2024-10, with the labels that each got.

#68 Profile card is added
  QuizQuestFrontend/src/App.jsx
  QuizQuestFrontend/src/components/ProfileCard.jsx
Labels: gssoc-ext, level3, hacktoberfest-accepted

#111 Enhanced profile card
  QuizQuestFrontend/index.html
  QuizQuestFrontend/public/images/male.png
  QuizQuestFrontend/src/components/ProfileCard.jsx
  QuizQuestFrontend/tailwind.config.js
  README.md
  repo_structure.txt
Labels: gssoc-ext, level3, hacktoberfest-accepted

#109 BUG: Footer aligned properly
  QuizQuestFrontend/src/components/Footer.jsx
Labels: gssoc-ext, level2, hacktoberfest-accepted

#120 Adding ContactUs Page
  QuizQuestFrontend/package.json
  QuizQuestFrontend/src/App.css
  QuizQuestFrontend/src/App.jsx
  QuizQuestFrontend/src/components/contact/ContactDetails.jsx
  QuizQuestFrontend/src/components/contact/ContactUsForm.jsx
  QuizQuestFrontend/src/components/contact/Contactform.jsx
  QuizQuestFrontend/src/data/countryCode.json
  QuizQuestFrontend/src/pages/ContactUs.jsx
  QuizQuestFrontend/tailwind.config.js
Labels: gssoc-ext, level3, hacktoberfest-accepted

#125 About section
  QuizQuestFrontend/src/App.jsx
  QuizQuestFrontend/src/components/ui/3d-card.jsx
  QuizQuestFrontend/src/components/ui/Timeline.jsx
  QuizQuestFrontend/src/images/signupss.png
  QuizQuestFrontend/src/pages/About.jsx
  QuizQuestFrontend/src/pages/home.jsx
  README.md
  repo_structure.txt
Labels: gssoc-ext, level3, hacktoberfest-accepted

#123 Adding Registration form
  QuizQuestFrontend/src/App.jsx
  QuizQuestFrontend/src/components/RegisterForm.jsx
  QuizQuestFrontend/src/components/RegistrationForm.jsx
  QuizQuestFrontend/src/pages/Registration.jsx
Labels: gssoc-ext, level3, hacktoberfest-accepted

#131 Bug/Update Website Title
  QuizQuestFrontend/index.html
  QuizQuestFrontend/src/App.jsx
  QuizQuestFrontend/src/components/Faqs.css
  QuizQuestFrontend/src/components/Faqs.jsx
  QuizQuestFrontend/src/components/contact/ContactUsForm.jsx
  QuizQuestFrontend/src/pages/Signup.jsx
Labels: gssoc-ext, level3, hacktoberfest-accepted

#136 Update twitter old icon
  QuizQuestFrontend/src/components/Footer.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted
